name: autofix.ci
run-name: autofix

on:
    push:
        branches:
            - main

concurrency:
    cancel-in-progress: false
    group: ${{ github.workflow }}

permissions:
    contents: read

jobs:
    autofix:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout sources
                uses: actions/checkout@v6

            -   name: Install java
                uses: actions/setup-java@v5
                with:
                    distribution: ${{ vars.JAVA_DISTRIBUTION }}
                    java-version: ${{ vars.JAVA_VERSION }}

            -   name: Install gradle
                uses: gradle/actions/setup-gradle@v6
                with:
                    gradle-version: ${{ vars.GRADLE_VERSION }}

            -   name: Format sources
                run: ./gradlew ktlintFormat

            -   name: Create commit
                continue-on-error: true
                uses: autofix-ci/action@v1
                with:
                    commit-message: "autofix ci"

            -   name: Archive reports
                uses: actions/upload-artifact@v7
                with:
                    if-no-files-found: ignore
                    name: reports
                    path: plugin*/build/reports/ktlint
                    retention-days: ${{ vars.ARTIFACT_RETENSION_DAYS }}
