name: test.ci
run-name: test

on:
    pull_request:

    workflow_dispatch:
        inputs:
            artifactRetentionDays:
                description: "Artifact retention days"
                required: false
                type: number

            cucumberTags:
                description: "Cucumber tags"
                required: false
                type: string

concurrency:
    cancel-in-progress: false
    group: ${{ github.workflow }}

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout sources
                uses: actions/checkout@v6

            -   name: Install java
                uses: actions/setup-java@v5
                with:
                    distribution: ${{ vars.JAVA_DISTRIBUTION }}
                    java-version: ${{ vars.JAVA_VERSION }}

            -   name: Install gradle
                uses: gradle/actions/setup-gradle@v6
                with:
                    gradle-version: ${{ vars.GRADLE_VERSION }}

            -   name: Run tests
                run: ./gradlew test -Ptags="${{ github.event.inputs.cucumberTags || vars.CUCUMBER_TAGS }}"

            -   name: Archive reports
                uses: actions/upload-artifact@v7
                with:
                    if-no-files-found: ignore
                    name: reports
                    path: plugin*/build/reports/cucumber.html
                    retention-days: ${{ github.event.inputs.artifactRetentionDays || vars.ARTIFACT_RETENSION_DAYS }}
